#Server Config
server:
  port: 10440

spring:
  application:
    name: api_gate_way

#注册中心配置信息
springcloud:
  register:
    port: 10000
    url: http://193.112.75.153:${springcloud.register.port}/eureka/

eureka: 
  client:
      registryFetchIntervalSeconds: 5 # eureka client刷新本地缓存时间（默认30秒）
      serviceUrl:
        defaultZone: ${springcloud.register.url}
      healthcheck:
        enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）

#路由规则
zuul:
  routes:
    common-service:
      path: /common/**
      serviceId: commonServer
  #是否开启重试功能
  retryable: true

ribbon:
  #同一个Server重试的次数(除去首次)
  MaxAutoRetries: 3
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
